### ISSUE TITLE
"Guest" account option w/ custom pricing structure

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#286]
**Is your feature request related to a problem? Please describe.**

We would like to increase the amount of work we do with influencers in different niches like our collaboration with @mtlfoodsnob (https://www.narcity.com/food/mtlfoodsnob)
The only issue to making this happen right now is they want more money per article than regular writers, since they have a following. Since they want more money, we have to make all the payments through invoices and Paypal so it's a mess. We also don't want them to have access to all our dashboards and stats.

**Describe the solution you'd like**

The Guest accounts should be regular Lilium users with no dashboard access and only access to their own articles and their payment dashboard.
The only other differentiator is we need to be able to set "fixed rates" for articles from these Guest users where the payment amount is not based off of the number of words in the article, it's based off a setting set in that Guest user's settings. We need to be able to enter custom amounts for these guest users as these influencers will have different rates negotiated.

**Are you currently using a workaround? If so, please describe it.**
Explained above.

**How important do you think this feature is?**
Pretty important if we want to scale.

**Comment by rykdesjardins** [comment]
This can be done using a role that doesn't give access to the dashboard and publishing pages (i.e. video team). We're already doing this :)

Custom pricing can be achieved with either a custom article type, or by adding items to invoices instead of articles. 

Closing this
