### ISSUE TITLE
Status box for content chains

### ISSUE THREAD

**Issue by rykdesjardins** [narcitymedia/lilium-cms#301]
**Is your feature request related to a problem? Please describe.**
At the moment, there is no way to get the full content chain URL from the interface. 

**Describe the solution you'd like**
A simple status box at the bottom of the content chain editor, pretty much like the article editor.

**Are you currently using a workaround? If so, please describe it.**
We're using the archive page to get the chain URL. It's all terrible. 

**How important do you think this feature is?**
Very important.

**Comment by Gaboik** [comment]
![image](https://user-images.githubusercontent.com/17395802/55363124-11201700-54aa-11e9-846d-50880d77c7be.png)
A status box was added to the content chain editor to display relevant info about a content chain
