### ISSUE TITLE
Settings page is not updating

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#306]
**Describe the bug**

When I try to edit the settings here, https://www.narcity.com/lilium/settings
It doesn't save when I refresh.

**To Reproduce**
1. Go to  the Settings page
2. Modify a field
3. Refresh
4. Nothing saved

**Expected behavior**

We should be able to update the settings of the website and it saves the settings.

**Section**

Settings page

**Additional context**

**Comment by rykdesjardins** [comment]
The setting page saves and works, but atm the CMS needs to be restarted for the changes to reflect. 

Making the settings "live" shouldn't be hard, but this require a message dispatched from one process to all other siblings, passing through the process manager. 

In English, that means it's a little more complicated than just updating a variable.

**Comment by chucklapointe** [comment]
Not important for now.
