### ISSUE TITLE
Content chains should have additional fields

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#308]
**Is your feature request related to a problem? Please describe.**

We need additional data in our content chains.

**Describe the solution you'd like**

The content chains should have a few more fields like "Culture" selection and have a "Clickable Slug" at the bottom, like on article edit pages.

**Are you currently using a workaround? If so, please describe it.**

No.

**How important do you think this feature is?**

Pretty important.

**Comment by Gaboik** [comment]
Closed by #314
