### ISSUE TITLE
Add a "Close" button somewhere in the Embed popup

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#319]
**Is your feature request related to a problem? Please describe.**

When you open the Embed popup, the only way to exit is to click on "esc" tab or insert an embed. I tested this with Laurie and she doesn't have the normal reflex of clicking on "esc".

**Describe the solution you'd like**

It would be great to have either a "dismiss" button at the bottom or a (X) button on the top right to get rid of the Embed popup.

**Are you currently using a workaround? If so, please describe it.**

I know that I can click on Escape, but I'm not sure most writers / editors will know. Will either have to explain or we can fix it before we launch.

**How important do you think this feature is?**

Medium

**Comment by Gaboik** [comment]
c7b19d01da4a02428fdaccad97404a6d11458838
