### ISSUE TITLE
A lot of really old embeds stopped rendering and won't resolve

### ISSUE THREAD

**Issue by rykdesjardins** [narcitymedia/lilium-cms#321]
**What section of the CMS does it affect?**
Embeds

**Is your feature fixing a problem? Please describe.**
With the V4 embed picker, we can easily refresh broken embeds. This is however not retroactive at the moment, and updating a website from V3 to V4 will not fix the old, broken embeds. 

I'm working on a small update script (4.0.3) to detect all embed wrappers in the content markup using JSDOM. It will then convert those broken embeds into V4 embeds, and should insert those in the database. 

This will also populate the embed picker.

**Steps needed to access / experience your new feature**
1 - Load an old article (+2yo)
2 - Notice broken embeds are not broken anymore
3 - Say "WOW" out loud, then add "that's awesome!" after smiling awkwardly a lil while everyone's looking at you for screaming at your computer.
4 - Repeat 3 as many times as necessary

**Comment by rykdesjardins** [comment]
Also, this will take forever to run, but it's one of the rare moments when performance is not at all the priority. 

Here's some pseudo code : 
```
GET cursor from FETCH all articles which contain embeds
FOR EACH cursor item {
    CREATE a JSDOM instance with the content
    GET all embeds from running a query selector
    FOR EACH embed found {
        REQUEST from the oembed Instagram endpoint
        INSERT oembed information in database
        UPDATE tag in dom with V4 embed placeholder
    }
    UPDATE article in database
}
```

**Comment by chucklapointe** [comment]
I had this open as an issue in my own to-do for at least 1 year.

If you can solve broken embeds automatically, even if it takes you 1 week to code, you will have legit saved hundreds of hours from our Editing team and the new writer we're recruiting for refreshing articles.

💯support this issue.

**Comment by rykdesjardins** [comment]
This is finished and ready for merge.
