### ISSUE TITLE
Add new "filters" in Publishing list page [Add date picker to filters]

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#333]
**Is your feature request related to a problem? Please describe.**

It seems that there are multiple people requesting to be able to filter by "published date" inside Lilium as well as "if sponsored content equals true".

**Describe the solution you'd like**

I think it would be great if we could:

- Add a calendar option that allows us to filter articles published on a certain date on [this page](https://www.narcity.com/lilium/publishing)
- Allow to filter articles showed on this [page](https://www.narcity.com/lilium/publishing) by certain "checkbox" criteria, so only show articles tagged with NSFW, Sponsored Content, etc.

**Are you currently using a workaround? If so, please describe it.**

Only workaround is to navigate the website on the front-end to find these articles and it seems very tedious.

**How important do you think this feature is?**

Not breaking

**Comment by rykdesjardins** [comment]
Added NSFW and Sponsored Content boxes in filter, 

Ref; d8caab6246119b011e51debcbc6cce27f8e47d3b
