### ISSUE TITLE
Possibility to schedule a post for publication in the future

### ISSUE THREAD

**Issue by rykdesjardins** [narcitymedia/lilium-cms#376]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to schedule a post for publication in the future (scheduled => published)

**Describe the solution you'd like**
A new status called "Scheduled" should exist, and should require the same rights as publish rights. The button would be located underneath "publish" in the list of actions. It would open up a pop-up requiring a date. 

Once the article has a scheduled date, a server job should be created with a timeout. Once the time is reached, the publication logic is triggered, and a notification is sent to the author. 

**Are you currently using a workaround? If so, please describe it.**
No.

**How important do you think this feature is?**
Important for productivity.

**Comment by Gaboik** [comment]
Deployed with #399
