### ISSUE TITLE
Add description field to images for "alt" tags and search

### ISSUE THREAD

**Issue by rykdesjardins** [narcitymedia/lilium-cms#377]
**Is your feature request related to a problem? Please describe.**
There is no alt tag for uploads. 

**Describe the solution you'd like**
A simple text box below the image credit for alt text. It could also be used to search for images. 

**Are you currently using a workaround? If so, please describe it.**
No alt. 

**How important do you think this feature is?**
Really important.

**Comment by Gaboik** [comment]
Closed in https://github.com/narcitymedia/lilium-cms/pull/411

**Comment by Gaboik** [comment]
Closed in #411
