### ISSUE TITLE
Stripe popup when I don't have the "Contractor" role

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#388]
**Describe the bug**

I am getting the Stripe contractor popup every time I open Lilium, even though I don't have the contractor role.
I'm not sure if this is happening for Editors as well.

**To Reproduce**
1. Impersonate my account
2. Get popup

**Expected behavior**

If I don't have the Contractor role, I shouldn't be getting a popup to enter my Stripe information.

**Screenshots**

<img width="1440" alt="Screen Shot 2019-05-26 at 2 34 46 PM" src="https://user-images.githubusercontent.com/31080672/58385797-f22e9480-7fc3-11e9-9abb-735c33734aa6.png">

**Section**
Everywhere

**Comment by rykdesjardins** [comment]
Found the issue. Will be fixed with next push later today!

**Comment by rykdesjardins** [comment]
This is only happening to admins btw, so editors are not affected.
