### ISSUE TITLE
Text can be inserted in upload placeholders

### ISSUE THREAD

**Issue by Gaboik** [narcitymedia/lilium-cms#396]
The upload placeholders that are inserted in the text editor seem to not have content editable `false`. This allows writers to drag text in them by mistake. The text will still show up in the text editor but, on the theme, are parsed out so text is missing from the article on the website.

**Comment by Gaboik** [comment]
Referenced in #398

**Comment by Gaboik** [comment]
On hold because we are not able to reproduce the issue at this point.
We did enable the 'noneditable' [TinyMCE plugin](https://www.tiny.cloud/docs/plugins/noneditable/) so hopefully there won't be more issues with this.
If the issue occurs again, we will need a thorough bug report that includes additional relevant information such as the Lilium user for whom the bug occurred, their operating system, their browser, the article for which it occurred and ideally, the specific embed that caused the problem.

**Comment by chucklapointe** [comment]
This should be fixed now.
@Gaboik and @rykdesjardins will look at creating a DB script to batch fix old embeds / uploads that don't have the "noneditable"

**Comment by Gaboik** [comment]
See #385  for a more detailed explanation of the problem
