### ISSUE TITLE
Force photo credits on Featured Images & Photo uploads

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#402]
**Describe the bug**

When the featured image is missing a photo credit, it throws off the MSN feed into a 502 bad gateway error.
Since so many factors depend on the photo credit being inserted properly, authors should never be able to inserted a featured image or any photo upload without a photo credit.

**To Reproduce**

1. Go to an article that is missing a photo credit on the Featured image
2. Go the MSN feed of that article
3. Get 502 Bad Gateway issue

**Expected behavior**

Photo uploads or featured images should never be allowed to be inserted without photo credits.

**Screenshots**

![unnamed](https://user-images.githubusercontent.com/31080672/59605810-9d230180-90dd-11e9-9ce0-5fd73dfc05dd.jpg)

**Section**
For instance: feeds, publishing page

**Additional context**

**Comment by Gaboik** [comment]
A few things will be necessary here
 - Fix the crash that happens at render time in the LML file caused by a `null` credit
 - Force a photo credit fort the featured image, like the uploads
 - + Implement a 'Gallery' section in the CMS, this will have to be a new issue

**Comment by Gaboik** [comment]
Commit e2b71c80e7334dd77744cd01ece81b2468d6434b fixed

> Force a photo credit fort the featured image, like the uploads

and

> (+) Implement a 'Gallery' section in the CMS, this will have to be a new issue

See #403
