### ISSUE TITLE
Kronos will race with Lilium during bootstrapping

### ISSUE THREAD

**Issue by rykdesjardins** [narcitymedia/lilium-cms#425]
**Describe the bug**
During startup, Gardener will spawn multiple instances of Lilium as well as a few services including Kronos. Some plugins need to schedule tasks with Kronos, and Kronos needs at least one Lilium instance to trigger the events. 

At the moment, Kronos and the Lilium instances are created as the same time, and at some point, one will require the other before it is ready to handle the events. 

**Expected behavior**
Since both parties can be ready first, they can both have a queue of events / requests, and process them once the two parties are ready. This can be orchestrated by Gardener. Both parties can let Gardener know when they're both ready. When it is the case, both parties can be notified that it's time to process the queues. 

This could be called the "global ready event". It could also only be fired when other processes are ready as well. This would not prevent Lilium from handling client requests, but would simply block cross-process tasks that require a racing process.

**Screenshot**
![image](https://user-images.githubusercontent.com/14999498/60690952-cbecf600-9e99-11e9-8814-7c30e13ef5eb.png)

**Section**
Core, Kronos, Gardener

**Comment by Gaboik** [comment]
This was solved in an earlier commit
