### ISSUE TITLE
Need AMEX to be added as a payment option in Lilium payment dashboard

### ISSUE THREAD

**Issue by kchrjapin** [narcitymedia/lilium-cms#473]
**Is your feature request related to a problem? Please describe.**
Yes, Narcity US contractors are being hired very quickly and we need additional payment options to be able to process their invoices in a timely manner

**Describe the solution you'd like**
Currently, only Visa/MC are payment options in Lilium. Need AMEX added. Stripe can process AMEX. NOTE: AMEX CVV codes are 4 digits, not 3 like Visa/MC.

**Are you currently using a workaround? If so, please describe it.**
No

**How important do you think this feature is?**
Very-- we are maxing our cards and limited by how much we can pay in one shot -- and our US team is growing SUPER FAST.

Thank you so much!

**Comment by Gaboik** [comment]
Closed in #493
