### ISSUE TITLE
Fetch less from GA Realtime (to 20 seconds, instead of 10 seconds)

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#500]
**Is your feature request related to a problem? Please describe.**

Our GA daily quota keeps getting busted, let's decrease the amount of fetches by double to give us more room in our limits.

**Describe the solution you'd like**

We should fetch less from GA Real-time API, I recommend twice less.

**Are you currently using a workaround? If so, please describe it.**

No

**How important do you think this feature is?**

Pretty important, mostly for the app & it's features

**Comment by rykdesjardins** [comment]
I'll make this a core setting :)

**Comment by chucklapointe** [comment]
Great!
