### ISSUE TITLE
Files (documents or photos) with special characters in their file name don't upload in Personal Details or Onboarding pop-up

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#533]
**Describe the bug**

When users try to photo IDs or work visa documents (in their Personal details page or in the Onboarding pop-up stage) that contain special characters in the file name, it doesn't upload and doesn't throw any errors.

**To Reproduce**

1. Login as a new contractor into Lilium
2. Try to upload files with a "é" or "ç" in the file name in the Photo ID field or Work Visa field
3. See that it doesn't update, nor throw any errors

**Expected behavior**

Contractors should be able to upload documents or photos with special characters.

**Section**

Lilium first time, or personal details page

**Comment by rykdesjardins** [comment]
This will simply require to URI encode / decode the file name in HTTP header.
